// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockAudioPlayer creates a new instance of MockAudioPlayer. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockAudioPlayer(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockAudioPlayer {
	mock := &MockAudioPlayer{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockAudioPlayer is an autogenerated mock type for the AudioPlayer type
type MockAudioPlayer struct {
	mock.Mock
}

type MockAudioPlayer_Expecter struct {
	mock *mock.Mock
}

func (_m *MockAudioPlayer) EXPECT() *MockAudioPlayer_Expecter {
	return &MockAudioPlayer_Expecter{mock: &_m.Mock}
}

// Play provides a mock function for the type MockAudioPlayer
func (_mock *MockAudioPlayer) Play(filepath string) error {
	ret := _mock.Called(filepath)

	if len(ret) == 0 {
		panic("no return value specified for Play")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(filepath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockAudioPlayer_Play_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Play'
type MockAudioPlayer_Play_Call struct {
	*mock.Call
}

// Play is a helper method to define mock.On call
//   - filepath
func (_e *MockAudioPlayer_Expecter) Play(filepath interface{}) *MockAudioPlayer_Play_Call {
	return &MockAudioPlayer_Play_Call{Call: _e.mock.On("Play", filepath)}
}

func (_c *MockAudioPlayer_Play_Call) Run(run func(filepath string)) *MockAudioPlayer_Play_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockAudioPlayer_Play_Call) Return(err error) *MockAudioPlayer_Play_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockAudioPlayer_Play_Call) RunAndReturn(run func(filepath string) error) *MockAudioPlayer_Play_Call {
	_c.Call.Return(run)
	return _c
}
