// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockCmdRunner creates a new instance of MockCmdRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCmdRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCmdRunner {
	mock := &MockCmdRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCmdRunner is an autogenerated mock type for the CmdRunner type
type MockCmdRunner struct {
	mock.Mock
}

type MockCmdRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCmdRunner) EXPECT() *MockCmdRunner_Expecter {
	return &MockCmdRunner_Expecter{mock: &_m.Mock}
}

// Run provides a mock function for the type MockCmdRunner
func (_mock *MockCmdRunner) Run(name string, args ...string) error {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(name, args)
	} else {
		tmpRet = _mock.Called(name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for Run")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, ...string) error); ok {
		r0 = returnFunc(name, args...)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockCmdRunner_Run_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Run'
type MockCmdRunner_Run_Call struct {
	*mock.Call
}

// Run is a helper method to define mock.On call
//   - name
//   - args
func (_e *MockCmdRunner_Expecter) Run(name interface{}, args ...interface{}) *MockCmdRunner_Run_Call {
	return &MockCmdRunner_Run_Call{Call: _e.mock.On("Run",
		append([]interface{}{name}, args...)...)}
}

func (_c *MockCmdRunner_Run_Call) Run(run func(name string, args ...string)) *MockCmdRunner_Run_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[1].([]string)
		run(args[0].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockCmdRunner_Run_Call) Return(err error) *MockCmdRunner_Run_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockCmdRunner_Run_Call) RunAndReturn(run func(name string, args ...string) error) *MockCmdRunner_Run_Call {
	_c.Call.Return(run)
	return _c
}
