# yaml-language-server: $schema=https://taskfile.dev/schema.json
version: "3"

vars:
  BINARY_NAME: cc-tools
  BIN_DIR: bin
  BINARY_PATH: "{{.BIN_DIR}}/{{.BINARY_NAME}}"
  MAIN_PATH: "./cmd/cc-tools"
  COVERAGE_DIR: coverage
  COVERAGE_FILE: "{{.COVERAGE_DIR}}/coverage.out"
  COVERAGE_HTML: "{{.COVERAGE_DIR}}/coverage.html"

tasks:
  default:
    desc: List available tasks
    cmds:
      - task --list

  # ─── Daily Development ─────────────────────────────────────────────────────

  test:
    desc: Run fast unit tests (-short, 30s timeout)
    aliases: [qt]
    preconditions:
      - sh: command -v gotestsum
        msg: "gotestsum not installed. Run: task tools-install"
    cmds:
      - gotestsum --format pkgname --format-hide-empty-pkg --hide-summary=skipped -- -tags=testmode -short -parallel 8 -timeout=30s ./...

  watch:
    desc: Auto-run tests on file changes (TDD essential!)
    preconditions:
      - sh: command -v gotestsum
        msg: "gotestsum not installed. Run: task tools-install"
    cmds:
      - gotestsum --watch --format pkgname --format-hide-empty-pkg --hide-summary=skipped -- -tags=testmode -short -parallel 8 -timeout=30s ./...

  lint:
    desc: Run golangci-lint
    aliases: [ql]
    cmds:
      - golangci-lint run --timeout=5m ./...

  fmt:
    desc: Format code (gofmt + goimports)
    cmds:
      - go fmt ./...
      - cmd: goimports -w -local github.com/riddopic/cc-tools .
        ignore_error: true

  # ─── Before Commit ─────────────────────────────────────────────────────────

  check:
    desc: Run all pre-commit checks (fmt + lint + test-race)
    aliases: [pre-commit]
    cmds:
      - task: fmt
      - task: lint
      - task: test-race

  test-race:
    desc: Run tests with race detector (-short, 60s timeout)
    preconditions:
      - sh: command -v gotestsum
        msg: "gotestsum not installed. Run: task tools-install"
    cmds:
      - gotestsum --format pkgname --hide-summary=skipped -- -tags=testmode -race -short -count=1 -timeout=60s ./...

  # ─── Build ─────────────────────────────────────────────────────────────────

  build:
    desc: Build the binary
    aliases: [q]
    sources:
      - "**/*.go"
      - go.mod
      - go.sum
    generates:
      - "{{.BINARY_PATH}}"
    cmds:
      - mkdir -p {{.BIN_DIR}}
      - go build -o {{.BINARY_PATH}} {{.MAIN_PATH}}

  install:
    desc: Install binary to $GOPATH/bin
    deps: [build]
    vars:
      GOPATH:
        sh: go env GOPATH
    cmds:
      - cp {{.BINARY_PATH}} {{.GOPATH}}/bin/{{.BINARY_NAME}}

  clean:
    desc: Remove build artifacts
    cmds:
      - rm -rf {{.BIN_DIR}} {{.COVERAGE_DIR}}
      - go clean -cache -testcache

  # ─── Utilities ─────────────────────────────────────────────────────────────

  coverage:
    desc: Generate test coverage report
    preconditions:
      - sh: command -v gotestsum
        msg: "gotestsum not installed. Run: task tools-install"
    cmds:
      - mkdir -p {{.COVERAGE_DIR}}
      - |
        PKGS_COVER=$(go list ./... | grep -v "/mocks")
        gotestsum --format pkgname -- -tags=testmode -coverprofile={{.COVERAGE_FILE}} -covermode=atomic $PKGS_COVER
      - go tool cover -html={{.COVERAGE_FILE}} -o {{.COVERAGE_HTML}}
      - go tool cover -func={{.COVERAGE_FILE}} | tail -n 1

  bench:
    desc: Run benchmarks
    preconditions:
      - sh: command -v gotestsum
        msg: "gotestsum not installed. Run: task tools-install"
    cmds:
      - "gotestsum --format pkgname -- -tags=testmode -bench=. -benchmem -benchtime=10s -run=^$ ./..."

  mocks:
    desc: Generate mocks using mockery
    preconditions:
      - sh: command -v mockery
        msg: "mockery not installed. Run: task tools-install"
    sources:
      - "**/*.go"
      - .mockery.yml
    cmds:
      - mockery --config .mockery.yml

  polish:
    desc: Format, auto-fix lint issues, and clean backup files
    cmds:
      - go fmt ./...
      - cmd: goimports -w -local github.com/riddopic/cc-tools .
        ignore_error: true
      - gofmt -w -s .
      - cmd: golangci-lint run --fix --timeout=5m ./...
        ignore_error: true
      - cmd: 'find . -type f \( -name "*.bak" -o -name "*.backup" -o -name "*.orig" \) -delete 2>/dev/null'
        ignore_error: true

  doctor:
    desc: Check development environment
    silent: true
    cmds:
      - 'echo -n "  Go:            " && go version | cut -d" " -f3'
      - 'echo -n "  golangci-lint: " && (golangci-lint version --short 2>/dev/null || echo "not installed")'
      - 'echo -n "  goimports:     " && (which goimports > /dev/null 2>&1 && echo "installed" || echo "not installed")'
      - 'echo -n "  gotestsum:     " && (gotestsum --version 2>/dev/null || echo "not installed (REQUIRED)")'
      - 'echo -n "  mockery:       " && (mockery 2>&1 | grep -o "v[0-9.]*" | head -1 || echo "not installed")'

  tools-install:
    desc: Install required development tools
    cmds:
      - go install github.com/golangci/golangci-lint/cmd/golangci-lint@latest
      - go install golang.org/x/tools/cmd/goimports@latest
      - go install gotest.tools/gotestsum@latest
      - go install github.com/vektra/mockery/v3@v3.2.5
