// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"context"

	mock "github.com/stretchr/testify/mock"

	"github.com/riddopic/cc-tools/internal/hooks"
)

// NewMockCommandRunner creates a new instance of MockCommandRunner. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockCommandRunner(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockCommandRunner {
	mock := &MockCommandRunner{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockCommandRunner is an autogenerated mock type for the CommandRunner type
type MockCommandRunner struct {
	mock.Mock
}

type MockCommandRunner_Expecter struct {
	mock *mock.Mock
}

func (_m *MockCommandRunner) EXPECT() *MockCommandRunner_Expecter {
	return &MockCommandRunner_Expecter{mock: &_m.Mock}
}

// LookPath provides a mock function for the type MockCommandRunner
func (_mock *MockCommandRunner) LookPath(file string) (string, error) {
	ret := _mock.Called(file)

	if len(ret) == 0 {
		panic("no return value specified for LookPath")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(file)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(file)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(file)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommandRunner_LookPath_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'LookPath'
type MockCommandRunner_LookPath_Call struct {
	*mock.Call
}

// LookPath is a helper method to define mock.On call
//   - file
func (_e *MockCommandRunner_Expecter) LookPath(file interface{}) *MockCommandRunner_LookPath_Call {
	return &MockCommandRunner_LookPath_Call{Call: _e.mock.On("LookPath", file)}
}

func (_c *MockCommandRunner_LookPath_Call) Run(run func(file string)) *MockCommandRunner_LookPath_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockCommandRunner_LookPath_Call) Return(s string, err error) *MockCommandRunner_LookPath_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockCommandRunner_LookPath_Call) RunAndReturn(run func(file string) (string, error)) *MockCommandRunner_LookPath_Call {
	_c.Call.Return(run)
	return _c
}

// RunContext provides a mock function for the type MockCommandRunner
func (_mock *MockCommandRunner) RunContext(ctx context.Context, dir string, name string, args ...string) (*hooks.CommandOutput, error) {
	var tmpRet mock.Arguments
	if len(args) > 0 {
		tmpRet = _mock.Called(ctx, dir, name, args)
	} else {
		tmpRet = _mock.Called(ctx, dir, name)
	}
	ret := tmpRet

	if len(ret) == 0 {
		panic("no return value specified for RunContext")
	}

	var r0 *hooks.CommandOutput
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...string) (*hooks.CommandOutput, error)); ok {
		return returnFunc(ctx, dir, name, args...)
	}
	if returnFunc, ok := ret.Get(0).(func(context.Context, string, string, ...string) *hooks.CommandOutput); ok {
		r0 = returnFunc(ctx, dir, name, args...)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*hooks.CommandOutput)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(context.Context, string, string, ...string) error); ok {
		r1 = returnFunc(ctx, dir, name, args...)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockCommandRunner_RunContext_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'RunContext'
type MockCommandRunner_RunContext_Call struct {
	*mock.Call
}

// RunContext is a helper method to define mock.On call
//   - ctx
//   - dir
//   - name
//   - args
func (_e *MockCommandRunner_Expecter) RunContext(ctx interface{}, dir interface{}, name interface{}, args ...interface{}) *MockCommandRunner_RunContext_Call {
	return &MockCommandRunner_RunContext_Call{Call: _e.mock.On("RunContext",
		append([]interface{}{ctx, dir, name}, args...)...)}
}

func (_c *MockCommandRunner_RunContext_Call) Run(run func(ctx context.Context, dir string, name string, args ...string)) *MockCommandRunner_RunContext_Call {
	_c.Call.Run(func(args mock.Arguments) {
		variadicArgs := args[3].([]string)
		run(args[0].(context.Context), args[1].(string), args[2].(string), variadicArgs...)
	})
	return _c
}

func (_c *MockCommandRunner_RunContext_Call) Return(commandOutput *hooks.CommandOutput, err error) *MockCommandRunner_RunContext_Call {
	_c.Call.Return(commandOutput, err)
	return _c
}

func (_c *MockCommandRunner_RunContext_Call) RunAndReturn(run func(ctx context.Context, dir string, name string, args ...string) (*hooks.CommandOutput, error)) *MockCommandRunner_RunContext_Call {
	_c.Call.Return(run)
	return _c
}
