// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockInputReader creates a new instance of MockInputReader. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockInputReader(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockInputReader {
	mock := &MockInputReader{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockInputReader is an autogenerated mock type for the InputReader type
type MockInputReader struct {
	mock.Mock
}

type MockInputReader_Expecter struct {
	mock *mock.Mock
}

func (_m *MockInputReader) EXPECT() *MockInputReader_Expecter {
	return &MockInputReader_Expecter{mock: &_m.Mock}
}

// IsTerminal provides a mock function for the type MockInputReader
func (_mock *MockInputReader) IsTerminal() bool {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for IsTerminal")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func() bool); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockInputReader_IsTerminal_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'IsTerminal'
type MockInputReader_IsTerminal_Call struct {
	*mock.Call
}

// IsTerminal is a helper method to define mock.On call
func (_e *MockInputReader_Expecter) IsTerminal() *MockInputReader_IsTerminal_Call {
	return &MockInputReader_IsTerminal_Call{Call: _e.mock.On("IsTerminal")}
}

func (_c *MockInputReader_IsTerminal_Call) Run(run func()) *MockInputReader_IsTerminal_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInputReader_IsTerminal_Call) Return(b bool) *MockInputReader_IsTerminal_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockInputReader_IsTerminal_Call) RunAndReturn(run func() bool) *MockInputReader_IsTerminal_Call {
	_c.Call.Return(run)
	return _c
}

// ReadAll provides a mock function for the type MockInputReader
func (_mock *MockInputReader) ReadAll() ([]byte, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for ReadAll")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() ([]byte, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() []byte); ok {
		r0 = returnFunc()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockInputReader_ReadAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadAll'
type MockInputReader_ReadAll_Call struct {
	*mock.Call
}

// ReadAll is a helper method to define mock.On call
func (_e *MockInputReader_Expecter) ReadAll() *MockInputReader_ReadAll_Call {
	return &MockInputReader_ReadAll_Call{Call: _e.mock.On("ReadAll")}
}

func (_c *MockInputReader_ReadAll_Call) Run(run func()) *MockInputReader_ReadAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockInputReader_ReadAll_Call) Return(bytes []byte, err error) *MockInputReader_ReadAll_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockInputReader_ReadAll_Call) RunAndReturn(run func() ([]byte, error)) *MockInputReader_ReadAll_Call {
	_c.Call.Return(run)
	return _c
}
