// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	mock "github.com/stretchr/testify/mock"
)

// NewMockOutputWriter creates a new instance of MockOutputWriter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockOutputWriter(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockOutputWriter {
	mock := &MockOutputWriter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockOutputWriter is an autogenerated mock type for the OutputWriter type
type MockOutputWriter struct {
	mock.Mock
}

type MockOutputWriter_Expecter struct {
	mock *mock.Mock
}

func (_m *MockOutputWriter) EXPECT() *MockOutputWriter_Expecter {
	return &MockOutputWriter_Expecter{mock: &_m.Mock}
}

// Write provides a mock function for the type MockOutputWriter
func (_mock *MockOutputWriter) Write(p []byte) (int, error) {
	ret := _mock.Called(p)

	if len(ret) == 0 {
		panic("no return value specified for Write")
	}

	var r0 int
	var r1 error
	if returnFunc, ok := ret.Get(0).(func([]byte) (int, error)); ok {
		return returnFunc(p)
	}
	if returnFunc, ok := ret.Get(0).(func([]byte) int); ok {
		r0 = returnFunc(p)
	} else {
		r0 = ret.Get(0).(int)
	}
	if returnFunc, ok := ret.Get(1).(func([]byte) error); ok {
		r1 = returnFunc(p)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockOutputWriter_Write_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Write'
type MockOutputWriter_Write_Call struct {
	*mock.Call
}

// Write is a helper method to define mock.On call
//   - p
func (_e *MockOutputWriter_Expecter) Write(p interface{}) *MockOutputWriter_Write_Call {
	return &MockOutputWriter_Write_Call{Call: _e.mock.On("Write", p)}
}

func (_c *MockOutputWriter_Write_Call) Run(run func(p []byte)) *MockOutputWriter_Write_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].([]byte))
	})
	return _c
}

func (_c *MockOutputWriter_Write_Call) Return(n int, err error) *MockOutputWriter_Write_Call {
	_c.Call.Return(n, err)
	return _c
}

func (_c *MockOutputWriter_Write_Call) RunAndReturn(run func(p []byte) (int, error)) *MockOutputWriter_Write_Call {
	_c.Call.Return(run)
	return _c
}
