// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockProcessManager creates a new instance of MockProcessManager. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockProcessManager(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockProcessManager {
	mock := &MockProcessManager{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockProcessManager is an autogenerated mock type for the ProcessManager type
type MockProcessManager struct {
	mock.Mock
}

type MockProcessManager_Expecter struct {
	mock *mock.Mock
}

func (_m *MockProcessManager) EXPECT() *MockProcessManager_Expecter {
	return &MockProcessManager_Expecter{mock: &_m.Mock}
}

// FindProcess provides a mock function for the type MockProcessManager
func (_mock *MockProcessManager) FindProcess(pid int) (*os.Process, error) {
	ret := _mock.Called(pid)

	if len(ret) == 0 {
		panic("no return value specified for FindProcess")
	}

	var r0 *os.Process
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(int) (*os.Process, error)); ok {
		return returnFunc(pid)
	}
	if returnFunc, ok := ret.Get(0).(func(int) *os.Process); ok {
		r0 = returnFunc(pid)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*os.Process)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(int) error); ok {
		r1 = returnFunc(pid)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockProcessManager_FindProcess_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'FindProcess'
type MockProcessManager_FindProcess_Call struct {
	*mock.Call
}

// FindProcess is a helper method to define mock.On call
//   - pid
func (_e *MockProcessManager_Expecter) FindProcess(pid interface{}) *MockProcessManager_FindProcess_Call {
	return &MockProcessManager_FindProcess_Call{Call: _e.mock.On("FindProcess", pid)}
}

func (_c *MockProcessManager_FindProcess_Call) Run(run func(pid int)) *MockProcessManager_FindProcess_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockProcessManager_FindProcess_Call) Return(process *os.Process, err error) *MockProcessManager_FindProcess_Call {
	_c.Call.Return(process, err)
	return _c
}

func (_c *MockProcessManager_FindProcess_Call) RunAndReturn(run func(pid int) (*os.Process, error)) *MockProcessManager_FindProcess_Call {
	_c.Call.Return(run)
	return _c
}

// GetPID provides a mock function for the type MockProcessManager
func (_mock *MockProcessManager) GetPID() int {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for GetPID")
	}

	var r0 int
	if returnFunc, ok := ret.Get(0).(func() int); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(int)
	}
	return r0
}

// MockProcessManager_GetPID_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'GetPID'
type MockProcessManager_GetPID_Call struct {
	*mock.Call
}

// GetPID is a helper method to define mock.On call
func (_e *MockProcessManager_Expecter) GetPID() *MockProcessManager_GetPID_Call {
	return &MockProcessManager_GetPID_Call{Call: _e.mock.On("GetPID")}
}

func (_c *MockProcessManager_GetPID_Call) Run(run func()) *MockProcessManager_GetPID_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockProcessManager_GetPID_Call) Return(n int) *MockProcessManager_GetPID_Call {
	_c.Call.Return(n)
	return _c
}

func (_c *MockProcessManager_GetPID_Call) RunAndReturn(run func() int) *MockProcessManager_GetPID_Call {
	_c.Call.Return(run)
	return _c
}

// ProcessExists provides a mock function for the type MockProcessManager
func (_mock *MockProcessManager) ProcessExists(pid int) bool {
	ret := _mock.Called(pid)

	if len(ret) == 0 {
		panic("no return value specified for ProcessExists")
	}

	var r0 bool
	if returnFunc, ok := ret.Get(0).(func(int) bool); ok {
		r0 = returnFunc(pid)
	} else {
		r0 = ret.Get(0).(bool)
	}
	return r0
}

// MockProcessManager_ProcessExists_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ProcessExists'
type MockProcessManager_ProcessExists_Call struct {
	*mock.Call
}

// ProcessExists is a helper method to define mock.On call
//   - pid
func (_e *MockProcessManager_Expecter) ProcessExists(pid interface{}) *MockProcessManager_ProcessExists_Call {
	return &MockProcessManager_ProcessExists_Call{Call: _e.mock.On("ProcessExists", pid)}
}

func (_c *MockProcessManager_ProcessExists_Call) Run(run func(pid int)) *MockProcessManager_ProcessExists_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(int))
	})
	return _c
}

func (_c *MockProcessManager_ProcessExists_Call) Return(b bool) *MockProcessManager_ProcessExists_Call {
	_c.Call.Return(b)
	return _c
}

func (_c *MockProcessManager_ProcessExists_Call) RunAndReturn(run func(pid int) bool) *MockProcessManager_ProcessExists_Call {
	_c.Call.Return(run)
	return _c
}
