package session_test

import (
	"fmt"
	"os"
	"path/filepath"
	"strings"
	"testing"

	"github.com/stretchr/testify/assert"
	"github.com/stretchr/testify/require"

	"github.com/riddopic/cc-tools/internal/session"
)

// Fixture lines mirror the shapes Claude Code writes to transcript JSONL files.
const (
	userPrompt   = `{"type":"user","message":{"role":"user","content":%q}}`
	userTextPart = `{"type":"user","message":{"role":"user","content":[{"type":"text","text":%q}]}}`
	metaReminder = `{"type":"user","isMeta":true,"message":{"role":"user",` +
		`"content":[{"type":"text","text":"<system-reminder>skills</system-reminder>"}]}}`
	toolResult = `{"type":"user","message":{"role":"user",` +
		`"content":[{"type":"tool_result","tool_use_id":"t1","content":"ok"}]}}`
	toolUse = `{"type":"assistant","message":{"role":"assistant",` +
		`"content":[{"type":"text","text":"working"},{"type":"tool_use","name":%q,"input":%s}]}}`
	aiTitle = `{"type":"ai-title","aiTitle":"fix-parser"}`
)

func prompt(text string) string   { return fmt.Sprintf(userPrompt, text) }
func textPart(text string) string { return fmt.Sprintf(userTextPart, text) }
func tool(name, input string) string {
	return fmt.Sprintf(toolUse, name, input)
}

func writeTranscript(t *testing.T, lines ...string) string {
	t.Helper()
	path := filepath.Join(t.TempDir(), "transcript.jsonl")
	require.NoError(t, os.WriteFile(path, []byte(strings.Join(lines, "\n")+"\n"), 0o600))
	return path
}

func TestParseTranscript_RealFormat(t *testing.T) {
	path := writeTranscript(t,
		metaReminder,
		prompt("Fix the bug in the parser"),
		tool("Read", `{"file_path":"/repo/config.go"}`),
		tool("Edit", `{"file_path":"/repo/main.go"}`),
		toolResult,
		tool("Bash", `{"command":"go test"}`),
		aiTitle,
		textPart("Looks good, commit it"),
		tool("Write", `{"file_path":"/repo/handler.go"}`),
		tool("Edit", `{"file_path":"/repo/main.go"}`),
		tool("NotebookEdit", `{"notebook_path":"/repo/nb.ipynb"}`),
	)

	summary, err := session.ParseTranscript(path)
	require.NoError(t, err)

	assert.Equal(t, 2, summary.TotalMessages, "only real prompts count")
	assert.Equal(t, "Fix the bug in the parser", summary.FirstPrompt)
	assert.Equal(t, []string{"Bash", "Edit", "NotebookEdit", "Read", "Write"}, summary.ToolsUsed)
	// Read targets are not modifications; edit order is preserved.
	assert.Equal(t, []string{"/repo/main.go", "/repo/handler.go", "/repo/nb.ipynb"}, summary.FilesModified)
}

func TestParseTranscript_FirstPromptSkipsNoise(t *testing.T) {
	tests := []struct {
		name  string
		lines []string
		want  string
		count int
	}{
		{
			name: "slash command uses its arguments",
			lines: []string{prompt("<command-message>ultrathink</command-message>\n" +
				"<command-name>/ultrathink</command-name>\n<command-args>Review the hooks</command-args>")},
			want:  "Review the hooks",
			count: 1,
		},
		{
			name: "slash command without arguments is skipped",
			lines: []string{
				prompt("<command-name>/clear</command-name>\n<command-args></command-args>"),
				prompt("Add a flag"),
			},
			want:  "Add a flag",
			count: 1,
		},
		{
			name: "bash mode input and output are skipped",
			lines: []string{
				prompt("<bash-input>task check</bash-input>"),
				prompt("<bash-stdout>ok</bash-stdout><bash-stderr></bash-stderr>"),
				prompt("Fix lint"),
			},
			want:  "Fix lint",
			count: 1,
		},
		{
			name: "local command output and caveats are skipped",
			lines: []string{
				prompt("<local-command-stdout>done</local-command-stdout>"),
				prompt("Caveat: The messages below were generated by the user while running local commands."),
				prompt("Ship it"),
			},
			want:  "Ship it",
			count: 1,
		},
		{
			name:  "embedded system reminders are removed",
			lines: []string{textPart("Rename the flag<system-reminder>hook context</system-reminder>")},
			want:  "Rename the flag",
			count: 1,
		},
		{
			name:  "only noise leaves the prompt empty",
			lines: []string{metaReminder, toolResult, prompt("<bash-input>ls</bash-input>")},
			want:  "",
			count: 0,
		},
	}

	for _, tt := range tests {
		t.Run(tt.name, func(t *testing.T) {
			summary, err := session.ParseTranscript(writeTranscript(t, tt.lines...))
			require.NoError(t, err)
			assert.Equal(t, tt.want, summary.FirstPrompt)
			assert.Equal(t, tt.count, summary.TotalMessages)
		})
	}
}

func TestParseTranscript_ReturnsEmptySummaryForEmptyFile(t *testing.T) {
	summary, err := session.ParseTranscript(writeTranscript(t))
	require.NoError(t, err)

	assert.Equal(t, 0, summary.TotalMessages)
	assert.Empty(t, summary.FirstPrompt)
	assert.Empty(t, summary.ToolsUsed)
	assert.Empty(t, summary.FilesModified)
}

func TestParseTranscript_ReturnsErrorForMissingFile(t *testing.T) {
	_, err := session.ParseTranscript("/tmp/nonexistent-transcript-xyz.jsonl")
	require.Error(t, err)
}

func TestParseTranscript_SkipsInvalidJSONLines(t *testing.T) {
	path := writeTranscript(t,
		prompt("Hello"),
		`not valid json`,
		tool("Edit", `{"file_path":"config.go"}`),
	)

	summary, err := session.ParseTranscript(path)
	require.NoError(t, err)

	assert.Equal(t, 1, summary.TotalMessages)
	assert.Equal(t, []string{"Edit"}, summary.ToolsUsed)
	assert.Equal(t, []string{"config.go"}, summary.FilesModified)
}

func TestParseTranscript_HandlesLongLines(t *testing.T) {
	// Tool results in real transcripts routinely exceed bufio's 64 KiB default.
	huge := `{"type":"user","message":{"content":[{"type":"tool_result","content":"` +
		strings.Repeat("x", 200_000) + `"}]}}`
	path := writeTranscript(t, huge, prompt("After the big result"))

	summary, err := session.ParseTranscript(path)
	require.NoError(t, err)
	assert.Equal(t, "After the big result", summary.FirstPrompt)
}
