// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockHooksFS creates a new instance of MockHooksFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockHooksFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockHooksFS {
	mock := &MockHooksFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockHooksFS is an autogenerated mock type for the HooksFS type
type MockHooksFS struct {
	mock.Mock
}

type MockHooksFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockHooksFS) EXPECT() *MockHooksFS_Expecter {
	return &MockHooksFS_Expecter{mock: &_m.Mock}
}

// CreateExclusive provides a mock function for the type MockHooksFS
func (_mock *MockHooksFS) CreateExclusive(name string, data []byte, perm os.FileMode) error {
	ret := _mock.Called(name, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for CreateExclusive")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, os.FileMode) error); ok {
		r0 = returnFunc(name, data, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHooksFS_CreateExclusive_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'CreateExclusive'
type MockHooksFS_CreateExclusive_Call struct {
	*mock.Call
}

// CreateExclusive is a helper method to define mock.On call
//   - name
//   - data
//   - perm
func (_e *MockHooksFS_Expecter) CreateExclusive(name interface{}, data interface{}, perm interface{}) *MockHooksFS_CreateExclusive_Call {
	return &MockHooksFS_CreateExclusive_Call{Call: _e.mock.On("CreateExclusive", name, data, perm)}
}

func (_c *MockHooksFS_CreateExclusive_Call) Run(run func(name string, data []byte, perm os.FileMode)) *MockHooksFS_CreateExclusive_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte), args[2].(os.FileMode))
	})
	return _c
}

func (_c *MockHooksFS_CreateExclusive_Call) Return(err error) *MockHooksFS_CreateExclusive_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHooksFS_CreateExclusive_Call) RunAndReturn(run func(name string, data []byte, perm os.FileMode) error) *MockHooksFS_CreateExclusive_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockHooksFS
func (_mock *MockHooksFS) ReadFile(name string) ([]byte, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHooksFS_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockHooksFS_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - name
func (_e *MockHooksFS_Expecter) ReadFile(name interface{}) *MockHooksFS_ReadFile_Call {
	return &MockHooksFS_ReadFile_Call{Call: _e.mock.On("ReadFile", name)}
}

func (_c *MockHooksFS_ReadFile_Call) Run(run func(name string)) *MockHooksFS_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHooksFS_ReadFile_Call) Return(bytes []byte, err error) *MockHooksFS_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockHooksFS_ReadFile_Call) RunAndReturn(run func(name string) ([]byte, error)) *MockHooksFS_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockHooksFS
func (_mock *MockHooksFS) Remove(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHooksFS_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockHooksFS_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - name
func (_e *MockHooksFS_Expecter) Remove(name interface{}) *MockHooksFS_Remove_Call {
	return &MockHooksFS_Remove_Call{Call: _e.mock.On("Remove", name)}
}

func (_c *MockHooksFS_Remove_Call) Run(run func(name string)) *MockHooksFS_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHooksFS_Remove_Call) Return(err error) *MockHooksFS_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHooksFS_Remove_Call) RunAndReturn(run func(name string) error) *MockHooksFS_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockHooksFS
func (_mock *MockHooksFS) Stat(name string) (os.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockHooksFS_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockHooksFS_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name
func (_e *MockHooksFS_Expecter) Stat(name interface{}) *MockHooksFS_Stat_Call {
	return &MockHooksFS_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *MockHooksFS_Stat_Call) Run(run func(name string)) *MockHooksFS_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockHooksFS_Stat_Call) Return(v os.FileInfo, err error) *MockHooksFS_Stat_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockHooksFS_Stat_Call) RunAndReturn(run func(name string) (os.FileInfo, error)) *MockHooksFS_Stat_Call {
	_c.Call.Return(run)
	return _c
}

// TempDir provides a mock function for the type MockHooksFS
func (_mock *MockHooksFS) TempDir() string {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for TempDir")
	}

	var r0 string
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	return r0
}

// MockHooksFS_TempDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'TempDir'
type MockHooksFS_TempDir_Call struct {
	*mock.Call
}

// TempDir is a helper method to define mock.On call
func (_e *MockHooksFS_Expecter) TempDir() *MockHooksFS_TempDir_Call {
	return &MockHooksFS_TempDir_Call{Call: _e.mock.On("TempDir")}
}

func (_c *MockHooksFS_TempDir_Call) Run(run func()) *MockHooksFS_TempDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockHooksFS_TempDir_Call) Return(s string) *MockHooksFS_TempDir_Call {
	_c.Call.Return(s)
	return _c
}

func (_c *MockHooksFS_TempDir_Call) RunAndReturn(run func() string) *MockHooksFS_TempDir_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockHooksFS
func (_mock *MockHooksFS) WriteFile(name string, data []byte, perm os.FileMode) error {
	ret := _mock.Called(name, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, os.FileMode) error); ok {
		r0 = returnFunc(name, data, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockHooksFS_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockHooksFS_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - name
//   - data
//   - perm
func (_e *MockHooksFS_Expecter) WriteFile(name interface{}, data interface{}, perm interface{}) *MockHooksFS_WriteFile_Call {
	return &MockHooksFS_WriteFile_Call{Call: _e.mock.On("WriteFile", name, data, perm)}
}

func (_c *MockHooksFS_WriteFile_Call) Run(run func(name string, data []byte, perm os.FileMode)) *MockHooksFS_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte), args[2].(os.FileMode))
	})
	return _c
}

func (_c *MockHooksFS_WriteFile_Call) Return(err error) *MockHooksFS_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockHooksFS_WriteFile_Call) RunAndReturn(run func(name string, data []byte, perm os.FileMode) error) *MockHooksFS_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
