// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockRegistryFS creates a new instance of MockRegistryFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockRegistryFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockRegistryFS {
	mock := &MockRegistryFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockRegistryFS is an autogenerated mock type for the RegistryFS type
type MockRegistryFS struct {
	mock.Mock
}

type MockRegistryFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockRegistryFS) EXPECT() *MockRegistryFS_Expecter {
	return &MockRegistryFS_Expecter{mock: &_m.Mock}
}

// MkdirAll provides a mock function for the type MockRegistryFS
func (_mock *MockRegistryFS) MkdirAll(path string, perm os.FileMode) error {
	ret := _mock.Called(path, perm)

	if len(ret) == 0 {
		panic("no return value specified for MkdirAll")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, os.FileMode) error); ok {
		r0 = returnFunc(path, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistryFS_MkdirAll_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'MkdirAll'
type MockRegistryFS_MkdirAll_Call struct {
	*mock.Call
}

// MkdirAll is a helper method to define mock.On call
//   - path
//   - perm
func (_e *MockRegistryFS_Expecter) MkdirAll(path interface{}, perm interface{}) *MockRegistryFS_MkdirAll_Call {
	return &MockRegistryFS_MkdirAll_Call{Call: _e.mock.On("MkdirAll", path, perm)}
}

func (_c *MockRegistryFS_MkdirAll_Call) Run(run func(path string, perm os.FileMode)) *MockRegistryFS_MkdirAll_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(os.FileMode))
	})
	return _c
}

func (_c *MockRegistryFS_MkdirAll_Call) Return(err error) *MockRegistryFS_MkdirAll_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistryFS_MkdirAll_Call) RunAndReturn(run func(path string, perm os.FileMode) error) *MockRegistryFS_MkdirAll_Call {
	_c.Call.Return(run)
	return _c
}

// ReadFile provides a mock function for the type MockRegistryFS
func (_mock *MockRegistryFS) ReadFile(name string) ([]byte, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for ReadFile")
	}

	var r0 []byte
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) ([]byte, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) []byte); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).([]byte)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistryFS_ReadFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'ReadFile'
type MockRegistryFS_ReadFile_Call struct {
	*mock.Call
}

// ReadFile is a helper method to define mock.On call
//   - name
func (_e *MockRegistryFS_Expecter) ReadFile(name interface{}) *MockRegistryFS_ReadFile_Call {
	return &MockRegistryFS_ReadFile_Call{Call: _e.mock.On("ReadFile", name)}
}

func (_c *MockRegistryFS_ReadFile_Call) Run(run func(name string)) *MockRegistryFS_ReadFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistryFS_ReadFile_Call) Return(bytes []byte, err error) *MockRegistryFS_ReadFile_Call {
	_c.Call.Return(bytes, err)
	return _c
}

func (_c *MockRegistryFS_ReadFile_Call) RunAndReturn(run func(name string) ([]byte, error)) *MockRegistryFS_ReadFile_Call {
	_c.Call.Return(run)
	return _c
}

// Remove provides a mock function for the type MockRegistryFS
func (_mock *MockRegistryFS) Remove(name string) error {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Remove")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string) error); ok {
		r0 = returnFunc(name)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistryFS_Remove_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Remove'
type MockRegistryFS_Remove_Call struct {
	*mock.Call
}

// Remove is a helper method to define mock.On call
//   - name
func (_e *MockRegistryFS_Expecter) Remove(name interface{}) *MockRegistryFS_Remove_Call {
	return &MockRegistryFS_Remove_Call{Call: _e.mock.On("Remove", name)}
}

func (_c *MockRegistryFS_Remove_Call) Run(run func(name string)) *MockRegistryFS_Remove_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockRegistryFS_Remove_Call) Return(err error) *MockRegistryFS_Remove_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistryFS_Remove_Call) RunAndReturn(run func(name string) error) *MockRegistryFS_Remove_Call {
	_c.Call.Return(run)
	return _c
}

// Rename provides a mock function for the type MockRegistryFS
func (_mock *MockRegistryFS) Rename(oldpath string, newpath string) error {
	ret := _mock.Called(oldpath, newpath)

	if len(ret) == 0 {
		panic("no return value specified for Rename")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, string) error); ok {
		r0 = returnFunc(oldpath, newpath)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistryFS_Rename_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Rename'
type MockRegistryFS_Rename_Call struct {
	*mock.Call
}

// Rename is a helper method to define mock.On call
//   - oldpath
//   - newpath
func (_e *MockRegistryFS_Expecter) Rename(oldpath interface{}, newpath interface{}) *MockRegistryFS_Rename_Call {
	return &MockRegistryFS_Rename_Call{Call: _e.mock.On("Rename", oldpath, newpath)}
}

func (_c *MockRegistryFS_Rename_Call) Run(run func(oldpath string, newpath string)) *MockRegistryFS_Rename_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].(string))
	})
	return _c
}

func (_c *MockRegistryFS_Rename_Call) Return(err error) *MockRegistryFS_Rename_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistryFS_Rename_Call) RunAndReturn(run func(oldpath string, newpath string) error) *MockRegistryFS_Rename_Call {
	_c.Call.Return(run)
	return _c
}

// UserHomeDir provides a mock function for the type MockRegistryFS
func (_mock *MockRegistryFS) UserHomeDir() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for UserHomeDir")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockRegistryFS_UserHomeDir_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'UserHomeDir'
type MockRegistryFS_UserHomeDir_Call struct {
	*mock.Call
}

// UserHomeDir is a helper method to define mock.On call
func (_e *MockRegistryFS_Expecter) UserHomeDir() *MockRegistryFS_UserHomeDir_Call {
	return &MockRegistryFS_UserHomeDir_Call{Call: _e.mock.On("UserHomeDir")}
}

func (_c *MockRegistryFS_UserHomeDir_Call) Run(run func()) *MockRegistryFS_UserHomeDir_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockRegistryFS_UserHomeDir_Call) Return(s string, err error) *MockRegistryFS_UserHomeDir_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockRegistryFS_UserHomeDir_Call) RunAndReturn(run func() (string, error)) *MockRegistryFS_UserHomeDir_Call {
	_c.Call.Return(run)
	return _c
}

// WriteFile provides a mock function for the type MockRegistryFS
func (_mock *MockRegistryFS) WriteFile(name string, data []byte, perm os.FileMode) error {
	ret := _mock.Called(name, data, perm)

	if len(ret) == 0 {
		panic("no return value specified for WriteFile")
	}

	var r0 error
	if returnFunc, ok := ret.Get(0).(func(string, []byte, os.FileMode) error); ok {
		r0 = returnFunc(name, data, perm)
	} else {
		r0 = ret.Error(0)
	}
	return r0
}

// MockRegistryFS_WriteFile_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'WriteFile'
type MockRegistryFS_WriteFile_Call struct {
	*mock.Call
}

// WriteFile is a helper method to define mock.On call
//   - name
//   - data
//   - perm
func (_e *MockRegistryFS_Expecter) WriteFile(name interface{}, data interface{}, perm interface{}) *MockRegistryFS_WriteFile_Call {
	return &MockRegistryFS_WriteFile_Call{Call: _e.mock.On("WriteFile", name, data, perm)}
}

func (_c *MockRegistryFS_WriteFile_Call) Run(run func(name string, data []byte, perm os.FileMode)) *MockRegistryFS_WriteFile_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string), args[1].([]byte), args[2].(os.FileMode))
	})
	return _c
}

func (_c *MockRegistryFS_WriteFile_Call) Return(err error) *MockRegistryFS_WriteFile_Call {
	_c.Call.Return(err)
	return _c
}

func (_c *MockRegistryFS_WriteFile_Call) RunAndReturn(run func(name string, data []byte, perm os.FileMode) error) *MockRegistryFS_WriteFile_Call {
	_c.Call.Return(run)
	return _c
}
