// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package mocks

import (
	"os"

	mock "github.com/stretchr/testify/mock"
)

// NewMockSharedFS creates a new instance of MockSharedFS. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockSharedFS(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockSharedFS {
	mock := &MockSharedFS{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockSharedFS is an autogenerated mock type for the SharedFS type
type MockSharedFS struct {
	mock.Mock
}

type MockSharedFS_Expecter struct {
	mock *mock.Mock
}

func (_m *MockSharedFS) EXPECT() *MockSharedFS_Expecter {
	return &MockSharedFS_Expecter{mock: &_m.Mock}
}

// Abs provides a mock function for the type MockSharedFS
func (_mock *MockSharedFS) Abs(path string) (string, error) {
	ret := _mock.Called(path)

	if len(ret) == 0 {
		panic("no return value specified for Abs")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (string, error)); ok {
		return returnFunc(path)
	}
	if returnFunc, ok := ret.Get(0).(func(string) string); ok {
		r0 = returnFunc(path)
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(path)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSharedFS_Abs_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Abs'
type MockSharedFS_Abs_Call struct {
	*mock.Call
}

// Abs is a helper method to define mock.On call
//   - path
func (_e *MockSharedFS_Expecter) Abs(path interface{}) *MockSharedFS_Abs_Call {
	return &MockSharedFS_Abs_Call{Call: _e.mock.On("Abs", path)}
}

func (_c *MockSharedFS_Abs_Call) Run(run func(path string)) *MockSharedFS_Abs_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSharedFS_Abs_Call) Return(s string, err error) *MockSharedFS_Abs_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSharedFS_Abs_Call) RunAndReturn(run func(path string) (string, error)) *MockSharedFS_Abs_Call {
	_c.Call.Return(run)
	return _c
}

// Getwd provides a mock function for the type MockSharedFS
func (_mock *MockSharedFS) Getwd() (string, error) {
	ret := _mock.Called()

	if len(ret) == 0 {
		panic("no return value specified for Getwd")
	}

	var r0 string
	var r1 error
	if returnFunc, ok := ret.Get(0).(func() (string, error)); ok {
		return returnFunc()
	}
	if returnFunc, ok := ret.Get(0).(func() string); ok {
		r0 = returnFunc()
	} else {
		r0 = ret.Get(0).(string)
	}
	if returnFunc, ok := ret.Get(1).(func() error); ok {
		r1 = returnFunc()
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSharedFS_Getwd_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Getwd'
type MockSharedFS_Getwd_Call struct {
	*mock.Call
}

// Getwd is a helper method to define mock.On call
func (_e *MockSharedFS_Expecter) Getwd() *MockSharedFS_Getwd_Call {
	return &MockSharedFS_Getwd_Call{Call: _e.mock.On("Getwd")}
}

func (_c *MockSharedFS_Getwd_Call) Run(run func()) *MockSharedFS_Getwd_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run()
	})
	return _c
}

func (_c *MockSharedFS_Getwd_Call) Return(s string, err error) *MockSharedFS_Getwd_Call {
	_c.Call.Return(s, err)
	return _c
}

func (_c *MockSharedFS_Getwd_Call) RunAndReturn(run func() (string, error)) *MockSharedFS_Getwd_Call {
	_c.Call.Return(run)
	return _c
}

// Stat provides a mock function for the type MockSharedFS
func (_mock *MockSharedFS) Stat(name string) (os.FileInfo, error) {
	ret := _mock.Called(name)

	if len(ret) == 0 {
		panic("no return value specified for Stat")
	}

	var r0 os.FileInfo
	var r1 error
	if returnFunc, ok := ret.Get(0).(func(string) (os.FileInfo, error)); ok {
		return returnFunc(name)
	}
	if returnFunc, ok := ret.Get(0).(func(string) os.FileInfo); ok {
		r0 = returnFunc(name)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(os.FileInfo)
		}
	}
	if returnFunc, ok := ret.Get(1).(func(string) error); ok {
		r1 = returnFunc(name)
	} else {
		r1 = ret.Error(1)
	}
	return r0, r1
}

// MockSharedFS_Stat_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'Stat'
type MockSharedFS_Stat_Call struct {
	*mock.Call
}

// Stat is a helper method to define mock.On call
//   - name
func (_e *MockSharedFS_Expecter) Stat(name interface{}) *MockSharedFS_Stat_Call {
	return &MockSharedFS_Stat_Call{Call: _e.mock.On("Stat", name)}
}

func (_c *MockSharedFS_Stat_Call) Run(run func(name string)) *MockSharedFS_Stat_Call {
	_c.Call.Run(func(args mock.Arguments) {
		run(args[0].(string))
	})
	return _c
}

func (_c *MockSharedFS_Stat_Call) Return(v os.FileInfo, err error) *MockSharedFS_Stat_Call {
	_c.Call.Return(v, err)
	return _c
}

func (_c *MockSharedFS_Stat_Call) RunAndReturn(run func(name string) (os.FileInfo, error)) *MockSharedFS_Stat_Call {
	_c.Call.Return(run)
	return _c
}
